### ISSUE TITLE
Ansible-friendly image?

### ISSUE THREAD

**Issue by rasputnik** [boxcutter/centos#18]
To be fair I've no idea if you use Ansible, but I can't provision
with it on this VM because it needs libselinux-python to work against
any linux with 'permissive' or higher settings.
(this previously worked on your images, was broken by
    https://github.com/boxcutter/centos/commit/149a60911a38b3e30749b82eb36ee52f12f9deda
).

I'm in a bit of a bind since I can't set yum to use a proxy until ansible works,
which requires the rpm be downloaded... catch 22.

Would you consider adding this to your images?

**Comment by rasputnik** [comment]
See PR #19 .

(most ks files had an 'Other stuff' section so I've added it there.
Did consider the CM management script but as Ansible is agentless there's 
very little we need other than the one Python binding, which is in the base repos for EL5 through 7).

**Comment by mattwillsher** [comment]
I've just hit up against the same issue - would be good to get this merged. :+1:

**Comment by rasputnik** [comment]
Any reason not to revert this? Especially considering the original addition was @mattwillsher

**Comment by mattwillsher** [comment]
I don't believe the change should be reverted to SELinux being entirely disabled.

The wider issue is the use of  --nobase in the Kickstart file, which is discouraged by RedHat. libselinux-python is included in the base install. The lack of libselinux-python also means no firewalld.

One work around would be to have a shell provisioner call before Ansible in the Vagrantfile to install the package.

Another option is to have a role in Ansible which installs any packages it needs before others run. The following worked for me in test playbook

``` yaml
  tasks:
    - yum: name=libselinux-python
```

**Comment by rasputnik** [comment]
Tried that - issue is we tend to run behind proxies, 
and I need Ansible to configure yum to install that rpm to make Ansible work. 

We could amend every Vagrantfile and do something in a provisioner but then we have to address the proxy issue in a shell script instead. Since we often _don't_ need a proxy we have to add conditional logic into that script, which is better handled at the Ansible level.

I don't expect everyone to be as allergic to selinux as I am, just adding the RPM to each .ks seems like a clean compromise.

**Comment by mattwillsher** [comment]
I agree on the package addition if installing base in its entirety isn't an option. 

@annawake what do you think?

**Comment by annawake** [comment]
In general, these images aim to install Just Enough OS (JEOS) to run a configuration management system (or Docker) to take care of installing any other things, so that's why we're not using `--base`.  We're also trying to make the images as slim as they can possibly be.

These VM-based images have a little bit more installed than we'd like only to accommodate VM guest tools of multiple varieties.

Installing SELinux is another concession made because it can't easily be set up by all the configuration management systems.

I would say that in this case, I would lean towards adding a `CM == 'ansible'` in `script/cmtool.sh` to make the extra RPM requirement needed for ansible be made explicit.

Though to be fair, it's also because Chef doesn't need this to run ;-)  However Chef also has a philosophy  that it tries to install all its dependencies needed, whereas all the other systems all have additional base requirements (like this selinux requirement for Ansible).  If ansible truly only needs just this one extra Linux RPM and it doesn't make the resultant `.box` file any bigger, I might consider adding it to the Kickstart - I just haven't had time yet to do this evaluation myself.

That being said, we've also had multiple requests for an ansible-equivalent of the `chefdk` option, where people want to have the ansible tools installed inside the image.  So I'd like the people who use ansible to decide whether or not this should be in all be in one `CM == 'ansible'` option or have another option like `CM == 'ansibledk'`

**Comment by rasputnik** [comment]
Thanks @annawake - I saw the various CM vars in there, but since Ansible is agentless it seemed like overkill. 

For me, we always run Ansible off the VM rather than on it in local mode so have no need for an actual Ansible install step, obviously that's just our use case though.

**Comment by rasputnik** [comment]
Did someone delete the 1.0.6 box ? 'vagrant up' is giving 403s trying to retrieve 1.0.16 (the last image we can use without the missing libselinux-python package).

vagrant tries to retrieve https://atlas.hashicorp.com/box-cutter/boxes/centos66/versions/1.0.16/providers/virtualbox.box which redirects to the CDN
at 
http://cdn.boxcutter.io/centos/virtualbox4.3.28/centos66-nocm-1.0.16.box , which 403s.

**Comment by rasputnik** [comment]
If the image has been rotated out and deleted, would anyone consider merging https://github.com/boxcutter/centos/pull/19 which would help us out of a bind? to address @annawake s concerns, this is all Ansible will need to get up and running.

**Comment by annawake** [comment]
Addressed by https://github.com/boxcutter/centos/commit/2311d1dead49a75a3c9f9b30ece09184e1a8154b
