### ISSUE TITLE
Unable to use custom ssh username/password while building the box?

### ISSUE THREAD

**Issue by dnataraj** [boxcutter/centos#3]
Hi, I have set the SSH_USERNAME, SSH_PASSWORD varables in Makefile.local, but it looks like this is failing. I can see that the variables are being taken into consideration - 

```
packer build -only=virtualbox-iso -var 'cm=chef' -var 'headless=true' -var 'update=true' -var 'version=1.0.13' -var 'ssh_username=stsdev' -var 'ssh_password=stsdev' -var 'install_vagrant_key=false' -var 'iso_path=/home/dnataraj/Downloads/' -var 'cm_version=latest' centos70-sts.json
```

And then make fails with the error - 

```
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Build was halted.
```

Have I missed anything obvious? Thanks.

**Comment by annawake** [comment]
The issue is that the username/password is hardcoded in the kickstart files in the `http/` subdirectory.  You'd have to change those as well.  Packer requires us to create the user in the kickstart, but with the RedHat variants, there isn't a good way to pass variables into one that I know of.

The SSH_USERNAME/SSH_PASSWORD defines weren't meant to be used in this way - for vagrant boxes, but rather when these templates are migrated over to the other box types (metal, cloud, container), where there the same kickstart files are not being used.

At some point, we may implement a [cheetah-like templating engine](http://www.cheetahtemplate.org) in boxcutter to allow parameterization of the kickstart files, but we're hoping that packer will support that at some point.  This is a necessary feature that packer currently lacks.
